# -*- coding: utf-8 -*-
"""Editar Aportes Públicos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxBnrv1firtpfY-Hyi1J4aswwhNw0nH7
"""

from numpy import fix
import pandas as pd
from pathlib import Path

data = pd.read_csv("Aportes_publicos_anual.csv",sep=";")
data = pd.DataFrame(data)

data = data.dropna(inplace=False)

data = data[data['Fecha de Pago'] != 'Sin derecho a pago.']

data = data.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

data['Nombre Partido'] = data['Nombre Partido'].apply(lambda x: x.strip().upper())

data['Nombre Partido'] = data['Nombre Partido'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

valores_partido = {
    "CIUDADANOS": "CIUDADANOS",
    "COMUNES": "COMUNES",
    "CONVERGENCIA SOCIAL": "CONVERGENCIA",
    "EVOLUCION POLITICA": "EVOPOLI",
    "FEDERACION REGIONALISTA VERDE SOCIAL": "FREVS",
    "IGUALDAD": "IGUALDAD",
    "IND CIUDADANOS": "IND",
    "IND COMUNES": "COMUNES",
    "IND CONVERGENCIA SOCIAL": "IND",
    "IND EVOLUCION POLITICA": "EVOPOLI",
    "IND FEDERACION REGIONALISTA VERDE SOCIAL": "IND",
    "IND IGUALDAD": "IND",
    "IND PARTIDO COMUNISTA DE CHILE": "IND",
    "IND PARTIDO CONSERVADOR CRISTIANO": "IND",
    "DEMOCRATA CRISTIANO": "IND",
    "IND PARTIDO ECOLOGISTA VERDE": "IND",
    "IND PARTIDO HUMANISTA": "IND",
    "IND PARTIDO LIBERAL DE CHILE": "IND",
    "IND PARTIDO POR LA DEMOCRACIA": "IND",
    "IND PARTIDO PROGRESISTA DE CHILE": "IND",
    "IND PARTIDO RADICAL DE CHILE": "IND",
    "IND PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": "IND",
    "IND PARTIDO REPUBLICANO DE CHILE": "IND",
    "IND PARTIDO SOCIALISTA DE CHILE": "IND",
    "IND RENOVACION NACIONAL": "IND",
    "IND REVOLUCION DEMOCRATICA": "IND",
    "IND UNION DEMOCRATA INDEPENDIENTE": "IND",
    "INDEPENDIENTE": "IND",
    "INDEPENDIENTES": "IND",
    "NUEVO TIEMPO": "NT",
    "COMUNISTA DE CHILE": "PCCH",
    "PARTIDO CONSERVADOR CRISTIANO": "PCC",
    "DEMOCRATA CRISTIANO": "PDC",
    "ECOLOGISTA VERDE": "PEV",
    "HUMANISTA": "PH",
    "LIBERAL DE CHILE": "PL",
    "PARTIDO NACIONAL CIUDADANO": "PNC",
    "POR LA DEMOCRACIA": "PPD",
    "PARTIDO PROGRESISTA DE CHILE (EX-PAIS PROGRESISTA)": "PRO",
    "PARTIDO RADICAL DE CHILE": "PR",
    "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": "PRI",
    "PARTIDO REPUBLICANO DE CHILE": "REPUBLICANO",
    "SOCIALISTA DE CHILE": "PS",
    "PARTIDO TRABAJADORES REVOLUCIONARIOS": "PTI",
    "PARTIDO UNION PATRIOTICA": "UPA",
    "RENOVACION NACIONAL": "RN",
    "REVOLUCION DEMOCRATICA": "RD",
    "UNION DEMOCRATA INDEPENDIENTE": "UDI",
    "UNION PATRIOTICA": "UPA"
}

data['ID_partido'] = data['Nombre Partido'].map(valores_partido)

data = data.dropna(inplace=False)
data.insert(0, 'ID_apu', range(0, len(data)))

data

from google.colab import files

data.to_csv('Aportes_publicos_anual.csv', encoding = 'utf-8-sig', index = False, sep=";") 
files.download('Aportes_publicos_anual.csv')

